= Devoxx4kids Microbit 
:Author:    Matthijs Thoolen  
:Email:     <matthijs.thoolen@codesquad.nl>
:Revision:  0.1

:toc:
:toc-title: Inhoud
:description: Devoxx4kids Microbit workshop 

In deze workshop gaan we samen aan de slag met de Microbit. Aan de hand van een aantal video's maken we opdrachten met de Microbit. We beginnen eerst met een uitleg, want wat is die Microbit eigenlijk? 

== Wat is de microbit?

video::0EUzE_Q3W98[youtube,options="modest",width=640,height=480]

hopelijk is zo duidelijk wat we gaan doen. Heb je vragen? Steek dan zeker je hand even op!

== Programmeer je naam in licht met een Microbit

video::ey6bCUwgXlg[youtube,options="modest",width=640,height=480,start=166]

. Start je browser
. Ga naar http://makecode.microbit.org/
. Klik op 'Nieuw project'
. Volg de instructies uit de video

Tip: mocht het te snel gaan, zet de video dan even op pauze

== Bouw een digitale dobbelsteen 

video::pY1bqTaSaJM[youtube,options="modest",width=640,height=480]

. Start je browser
. Ga naar http://makecode.microbit.org/
. Klik op 'Nieuw project'
. Volg de instructies uit de video

Tip: mocht het te snel gaan, zet de video dan even op pauze

== vierde video

beschrijving bij derde video

== vijfde video

beschrijving bij derde video

== zesde video

beschrijving bij derde video

== extra opdrachten

mogelijke extra opdrachten
